# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RRBoIGULGcmK2GqTIkALa3384UO5ufa9
"""

import os
import shutil

if os.path.exists("CS"):
  shutil.rmtree("CS")
os.mkdir("CS")
file = open('homework.txt','r')
with open('homework.txt','w') as file:
  file.write("4112029022_湯文中")
file = open('homework.txt','r')
content = file.read()
print(content)

shutil.move("homework.txt", "CS")
a = os.path.getsize("CS/homework.txt")
b = os.path.getmtime("CS/homework.txt")
print(a,b)